name: momday_app
description: Cross-Platform Application for Momday
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  intl: ^0.17.0
  xml: ^5.0.0
  cupertino_icons: ^0.1.2
  http: ^0.13.1
  observable: ^0.23.0
  html_unescape: 1.0.1+2
  shared_preferences: 0.5.0
  url_launcher: 4.0.3
  flutter_pagewise: 1.2.0
  flutter_html: 0.8.2
  flutter_webview_plugin: ^0.3.11
  trotter: 1.0.2
  cached_network_image: ^3.0.0
  flutter_typeahead: 0.5.2
  video_player: ^0.10.12+2
  integration_test: ^1.0.2+2
  flutter_datetime_picker: ^1.4.0
  image_picker: ^0.6.0+9
  country_code_picker: ^1.6.2
#  permission: 0.1.1
  image_cropper: ^1.3.1
  image: ^3.0.2
  flutter_credit_card: 0.1.3
  awesome_card: ^1.1.0
#  permission_handler: 2.1.0

dev_dependencies:
  flutter_launcher_icons:

flutter_icons:
  android: true
  ios: true
  image_path_android: "assets/icons/logo_out.png"
  image_path_ios: "assets/icons/logo_out.png"
  adaptive_icon_background: "#FFFFFFFF"

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  assets:
    - assets/icons/
    - assets/images/
    - assets/images/samples/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
  fonts:
    - family: ProximaNova
      fonts:
        - asset: assets/fonts/ProximaNova-Regular_0.otf
        - asset: assets/fonts/ProximaNova-Bold_0.otf
          weight: 700
        - asset: assets/fonts/ProximaNova-Extrabld_0.otf
          weight: 800
        - asset: assets/fonts/ProximaNova-Light_0.otf
          weight: 300
        - asset: assets/fonts/ProximaNova-Semibold_0.otf
          weight: 600
    - family: FrutigerLTArabic
      fonts:
        - asset: assets/fonts/FrutigerLTArabic-55Roman_2.ttf
        - asset: assets/fonts/FrutigerLTArabic-65Bold_0.ttf
          weight: 700
        - asset: assets/fonts/FrutigerLTArabic-65Bold_0.ttf
          weight: 800
        - asset: assets/fonts/FrutigerLTArabic-45Light_0.ttf
          weight: 300
        - asset: assets/fonts/FrutigerLTArabic-65Bold_0.ttf
          weight: 600
    - family: VAG
      fonts: 
        - asset: assets/fonts/VAGRoundedStd-Bold.otf
          weight: 700
        - asset: assets/fonts/VAGRoundedStd-Thin.otf
          weight: 300


androidX: true