Map<String, String> arabic = {
  'home': 'الرئيسية',
  'celebrities': 'المشاهير',
  'shop': 'تسوقي',
  'activities': 'النشاطات',
  'momsay': 'المنتدى',
  'featured_items': 'السلع المميزة',
  'brands': 'الماركات',
  'featured_stores': 'المحلات المميزة',
  'search': 'ابحث',
  'preloved': 'مستعملة',
  'new': 'جديدة',
  'menu': 'القائمة',
  'items': 'سلع',
  'shop_now': 'اشتر الآن',
  'my_account': 'حسابي',
  'log_out': 'تسجيل الخروج',
  'language': 'اللغة',
  'log_in_with_facebook': 'تسجيل الدخول باستخدام فيسبوك',
  'log_in_with_google': 'تسجيل الدخول باستخدام جوجل',
  'or': 'أو',
  'email': 'البريد الإلكتروني',
  'dob': 'تاريخ الولادة (ي ي /ش ش /س س س س)',
  'gender': 'الجنس',
  'password': 'كلمة المرور',
  'log_in': 'تسجيل الدخول',
  'forgot_password': 'هل نسيت كلمة المرور؟',
  'sign_up': 'أنشئي حساباً',
  'username': 'اسم المستخدم',
  'confirm_password': 'تأكيد كلمة المرور',
  'by_submitting': 'تقديمك لهذه الاستمارة يعني موافقتك على ',
  'terms_of_service': 'شروط الخدمة ',
  'and': 'و',
  'privacy_policy': 'سياسة الخصوصية',
  'first_name': 'الاسم الأول',
  'last_name': 'اسم العائلة',
  'field_required': 'هذا الحقل إلزامي',
  'password_length': 'كلمة المرور يجب أن تكون بين 4 و20 حرفاً',
  'confirm_password_different': 'الرجاء إدخال ذات كلمة المرور التي أدخلتها في حقل كلمة المرور',
  'not_valid_email': 'الرجاء إدخال بريد إلكتروني صحيح',
  'not_valid_dob': 'الرجاء إدخال تاريخ ولادة صحيح',
  'guest_user': 'حساب زائر',
  'send': 'أرسل',
  'forgot_password_instructions': 'أدخلي عنوان بريدك الإلكتروني المرتبط بهذا الحساب، ثم اضغطي أرسل لنرسل لك رابط إعادة تعيين كلمة المرور.',
  'check_email_forgot': 'تم إرسال رابط إلى بريدك الإلكتروني، الرجاء مراجعة بريدك لمتابعة العملية.',
  'price': 'السعر',
  'customer_reviews': 'آراء الزبائن',
  'review_single': 'رأي',
  'review_plural': 'آراء',
  'out_of': 'من أصل',
  'write_review': 'اكتبي رأيك',
  'need_login': 'يجب أن تقومي بتسجيل الدخول ل',
  'add_this_item_to_wishlist': 'إضافة هذه السلعة إلى قائمة الرغبات',
  'logout_successful': 'تم تسجيل الخروج بنجاح',
  'item_added_successfully': 'تمت الإضافة بنجاح',
  'item_moved_successfully': 'تم النقل بنجاح',
  'go_to_cart': 'اذهب إلى الحقيبة',
  'go_to_wishlist': 'اذهب إلى قائمة الرغبات',
  'subtotal': 'الإجمالي',
  'checkout': 'الدفع',
  'go_back_to_shopping': 'عودي إلى التسوق',
  'confirm_remove_item_from_cart': 'هل أنت متأكدة أنك تريدين إزالة السلعة من حقيبتك؟',
  'cancel': 'تراجع',
  'remove': 'أزل',
  'cart_empty': 'حقيبتك فارغة!',
  'wishlist_empty': 'قائمة رغباتك فارغة!',
  'move_to_cart': 'انقليها إلى الحقيبة',
  'sort': 'الترتيب',
  'show_all_categories': 'أعرض كل التصنيفات',
  'all_categories': 'كل التصنيفات',
  'all': 'الكل',
  'name': 'الاسم',
  'filter': 'الفرز',
  'brand': 'الماركة',
  'clear_filters': 'ألغ الفرز',
  'no_items_found': 'لم نجد أي شيء',
  'error_occurred': 'يبدو أن خطأ ما قد حصل',
  'error': 'خطأ',
  'choose_category': 'اختاري التصنيف',
  'high_to_low': 'من الأكثر إلى الأقل',
  'low_to_high': 'من الأقل إلى الأكثر',
  'my_cart': 'حقيبتي',
  'quantity': 'العدد',
  'move_to_wishlist': 'انقل إلى قائمة الرغبات',
  'wishlist': 'قائمة الرغبات',
  'my_wishlist': 'رغباتي',
  'quantity_available': 'الكمية المتوفرة',
  'in_stock': 'متوفر',
  'out_of_stock': 'غير متوفر',
  'about': 'About',
  'faq': 'الأسئلة الأكثر شيوعاً',
  'contact_us': 'اتصلي بنا',
  'notifications': 'الإشعارات',
  'new_item': 'بضاعة جديدة',
  'preloved_item': 'بضاعة مستعملة',
  'description': 'التفاصيل',
  'specifications': 'المواصفات',
  'sku': 'كود التخزين التعريفي',
  'related_items': 'السلع المشابهة',
  'new_search': 'بحث جديد',
  'back_to_home': 'عودي إلى الرئيسية',
  'welcome_to_momday': 'أهلاً بكِ في momday',
  'my_profile': 'ملفي',
  'my_addresses': 'عناويني',
  'location': 'الموقع',
  'advanced_settings': 'الإعدادات المتقدمة',
  'welcome': 'أهلاً بك',
  'create_an_account': 'أنشئي حساباً',
  'no_worries': 'لا تقلقي!',
  'dont_have_an_account': 'ليس لديك حساب؟',
  'select_address': 'اختاري العنوان',
  'add_new_address': 'أضيفي عنواناً جديداً',
  'add_address': 'أضيفي العنوان',
  'pay': 'إدفع',
  'pay_with_payfort':'الدفع بواسطة الفيزا',
  'pay_with_aramex':'الدفع بواسطة أرامكس',
  'country': 'البلد',
  'city': 'المدينة',
  'lebanon': 'لبنان',
  'address': 'العنوان',
  'failed_to_add_address': 'فشلت عملية إضافة العنوان',
  'enter_less_than_2_lines': 'الرجاء عدم إدخال أكثر من سطرين',
  'continue_to_payment': 'تابعي إلى الدفع',
  'no_address_selected': 'لم يتم اختيار عنوان',
  'change_address': 'غيري العنوان',
  'delete_address': 'احذفي العنوان',
  'confirm_remove_address': 'هل أنت متأكدة أنك تريدين إزالة هذا العنوان؟',
  'no_addresses': 'لم تضيفي أي عنوان بعد!',
  'clear_cache': 'نظفي مخبأ المعلومات',
  'clear_session_data': 'نظفي معلومات الجلسة',
  'confirm_clear_cache': 'هل أنت متأكدة من رغبتك في تنظيف مخبأ المعلومات؟ هذا سيجعل التطبيق بطيئاً لبعض الوقت',
  'confirm_clear_session_data': 'هل أنت متأكدة من رغبتك في تنظيف معلومات الجلسة؟ هذا سيقوم بتسجيل خروجك',
  'advanced_settings_warning': 'لا تقومي بهذه العمليات إلا إذا طلب منك مهندسوا الدعم',
  'add_your_review': 'أضف رأيك',
  'already_reviewed': 'لقد أبديت رأيك بهذه المادة',
  'share_your_review': 'شاركينا برأيك عن هذه المادى',
  'rate_this_item': 'قيم هذه السلعة',
  'provide_rating': 'الرجاء وضع تقييم',
  'review_length_restrictions': 'الرجاء كتابة ما بين 25 و1000 حرف',
  'review_submitted': 'تم إرسال رأيك، سوف يظهر للآخرين بعد أن يوافق عليه المدير',
  'edit': 'غيري',
  'change_password': 'غيري كلمة المرور',
  'save_changes': 'احفظي التغييرات',
  'in_my_wishlist': 'أضيفت إلى الرغبات',
  'in_my_cart': 'أضيفت إلى الحقيبة',
  'add_to_my_store': 'أضيفي إلى متجري',
  'in_my_my_store': 'أضيفت إلى متجري',
  'remove_from_my_store': 'أزيلي من متجري',
  'my_store': 'متجري',
  'sort_by': 'رتبي وفق',
  'apply_filters': 'طبقي الفرز',
  'category': 'التصنيف',
  'products': 'المنتجات',
  'coming_soon': 'قريباً',
  'try_again': 'أعيدي المحاولة',
  'report_issue': 'بلغي عن المشكلة',
  'no_related_products': 'لم نجد أي منتجات مشابهة',
  'view_all': 'شاهدي الكل',
  'view_more': 'شاهدي المزيد',
  'moms_best_daily_kit': 'أفضل عدة يومية  للأم',
  'momday_description': 'تابعي كل مستلزمات الأطفال والأنشطة الرائجة، وجربي الأمومة على طريقة مشاهيرك المفضلين!',
  'visit_website': 'زوري الموقع',
  'read_full_article': 'اقرأي المقالة',
  'write_your_comment': 'اكتبي تعليقك',
  'add_comment': 'أضيفي التعليق',
  'comment_single': 'تعليق',
  'comment_plural': 'تعليق',
  'like_this_post': 'تبدي إعجابك',
  'comment_on_this_post': 'تعلقي على هذا المقال',
  'view_details': 'شاهدي التفاصيل',
  'event_details': 'تفاصيل الحدث',
  'view_author_bio': 'نبذة عن الكاتب',
  'biography': 'نبذة',
  'reply': 'أجيبي',
  'view_replies': 'شاهدي الإجابات',
  'hide_replies': 'أخفي الإجابات',
  'add_your_reply': 'أضيفي إجابتك',
  'my_list': 'قائمة معروضاتي',
  'upload_image':'تحميل صورة',
  'upload_video':'تحميل فيديو',
  'upload_image_header':'تأكدي من تحميل ٤ صور كحد أقصى لسلعتك',
  "upload_video_header": "حمِّلي مقطع فيديو مدته ٥ ثوانٍ يعرض تفاصيل سلعتك",
  'photos':'الصور',
  'video':'الفيديو',
  'image_from_gallery':'تحميل من المعرض',
  'image_from_camera':'التقاط صورة',
  'video_from_gallery':'تحميل من المعرض',
  'video_from_camera':'التقاط فيديو',
  'delete_attachment': 'حذف المرفق',
  'delete_attachment_confirm': 'هل أنت متأكدة من أنك تريدين حذف هذا الملف؟',
  'delete':'حذف',
  'next': 'التالي',
  'previous':'السابق',
  'contact_info':'معلومات للتواصل',
  'contact_info_details': 'أضفي البريد الإلكتروني ورقم الهاتف وموقع الأخذ',
  'contact_info_disclaimer': 'يرجى ملاحظة أن رقم هاتفك لن يظهر في منشورك ، وسوف نستخدمه فقط للاتصال بك لترتيب استلام السلعة',
  'phone':'رقم الهاتف',
  'pickup':'موقع الأخذ',
  'pickup_hint':'اكتبي موقع الأخذ',
  'donate': 'تبرع',
  'donate_to': 'تبرع لأجل',
  'donation_ask': 'هل ترغبين في التبرع للجمعيات الخيرية؟',
  'donation_msg': 'بالتبرع أنت توافقين على أن أرباح السلعة الخاصة بك ستكون مخصصة بالكامل للجمعية الخيرية',
  'donation_msg_buyer':'أرباح هذه السلعة ستكون مخصصة بالكامل للجمعيات الخيرية',
  'no_thanks':'لا شكرا',
  'item_name': 'اسم السلعة',
  'item_name_hint': "اكتبي اسم السلعة",
  'description_hint': 'صفي السلعة في بضع كلمات',
  'brand_hint':"اختاري ماركة السلعة",
  'subcategory_hint':"اختاري الفئة الفرعية للسلعة",
  'category_hint':"اختاري فئة السلعة",
  'condition_hint':"اختاري حالة السلعة",
  'type':'النوع',
  'good':'جيد',
  'fair':'وسط',
  'excellent':'ممتاز',
  'size':'القياس',
  'standard_size':'قياس واحد',
  'size_hint': 'القياس',
  'color':'اللون',
  'color_hint':'اللون',
  'price_hint':'اكتبي سعر السلعة',
  'add_item': 'اضافة سلعة',
  'donated':'تبرع',
  'condition':'الحالة',
  'loading_video': 'جار تحميل الفيديو',
  'preview_video' : 'معاينة الفيديو',
  'close': 'إغلاق',
  'pending' : 'قيد الانتظار',
  'inactive': 'غير فعال',
  'active': 'فعال',
  'sold':'تم البيع',
  'charity':'الاعمال الخيرية',
  'delete_myitem':'حذف السلعة',
  'delete_myitem_confirm':'هل أنت متأكدة من أنك تريدين حذف هذه السلعة؟',
  'deactivate_myitem':'تعطيل السلعة',
  'deactivate_myitem_confirm':'هل أنت متأكدة من أنك تريدين تعطيل هذه السلعة؟',
  'deactivate': 'تعطيل',
  'specify_options': 'يرجى تحديد الخيارات التالية',
  'select_option': 'يرجى تحديد',
  'activate': 'تفعيل',
  'invalid_phoneNumber': 'رقم هاتف غير مقبول',
  'video_required' : 'يرجى تحميل فيديو',
  'image_required' : 'يرجى تحميل صورة واحدة على الأقل',
  'expires': 'تنتهي الصلاحية',
  'view_remark': 'عرض الملاحظة',
  'ok': 'موافق',
  'dimensions': 'أبعاد',
  'width': 'عرض',
  'height': 'ارتفاع',
  'length': 'طول',
  'weight': 'وزن',
  'dimensions_unit' : 'وحدة الأبعاد',
  'weight_unit' : 'وحدة الوزن',
  'uploading_attachment':'جار تحميل المرفق',
  'comment_submitted': 'تم إرسال تعليقك، سوف يظهر للآخرين بعد أن يوافق عليه المدير',
  'comment_error':'خطأ حصل في نشر تعليق. حاول مرة أخرى في وقت لاحق.',
  'submit': 'تقديم',
  'product_attributes': 'سمات المنتج',
  'rejected':'مرفوض',
  'reward_points': '',
  'final_price':'سعر المنتج النهائي'
};