Map<String, String> english = {
  'home': 'home',
  'celebrities': 'celebrities',
  'shop': 'shop',
  'activities': 'activities',
  'momsay': 'momsay',
  'featured_items': 'featured items',
  'brands': 'brands',
  'featured_stores': 'featured stores',
  'search': 'search',
  'preloved': 'pre-loved',
  'new': 'new',
  'items': 'items',
  'shop_now': 'shop now',
  'my_account': 'my account',
  'log_out': 'log out',
  'language': 'Language',
  'log_in_with_facebook': 'log in with facebook',
  'log_in_with_google': 'log in with google',
  'or': 'or',
  'email': 'email',
  'dob': 'Date of birth',
  'gender': 'gender',
  'password': 'password',
  'log_in': 'log in',
  'forgot_password': 'forgot your password?',
  'sign_up': 'sign up',
  'confirm_password': 'confirm password',
  'by_submitting': 'by submitting this form, you agree to the ',
  'terms_of_service': 'terms of service ',
  'and': 'and',
  'privacy_policy': ' privacy policy',
  'first_name': 'first name',
  'last_name': 'last name',
  'field_required': 'this field is required',
  'password_length': 'password must be between 4 and 20 characters',
  'confirm_password_different':
      'please enter the same value you entered in the password field',
  'not_valid_email': 'not a valid email address',
  'not_valid_dob': 'date of birth format should be dd/mm/yyyy',
  'guest_user': 'guest user',
  'send': 'Send',
  'forgot_password_instructions':
      'enter the email address associated with your account, then click send to have a password reset link emailed to you.',
  'check_email_forgot':
      'a link has been sent to your email, please check your email to proceed.',
  'price': 'price',
  'customer_reviews': 'customer reviews',
  'review_single': 'review',
  'review_plural': 'reviews',
  'out_of': 'out of',
  'write_review': 'write a review',
  'need_login': 'you need to be logged in to ',
  'add_this_item_to_wishlist': 'add this item to wishlist',
  'logout_successful': 'you\'ve been logged out successfully',
  'item_added_successfully': 'item added successfully',
  'item_moved_successfully': 'item moved successfully',
  'go_to_cart': 'go to cart',
  'go_to_wishlist': 'go to wishlist',
  'subtotal': 'subtotal',
  'checkout': 'checkout',
  'go_back_to_shopping': 'back to shopping',
  'confirm_remove_item_from_cart':
      'are you sure you want to remove item from cart?',
  'cancel': 'cancel',
  'remove': 'remove',
  'cart_empty': 'your cart is empty!',
  'wishlist_empty': 'your wishlist is empty!',
  'move_to_cart': 'move to cart',
  'sort': 'sort',
  'show_all_categories': 'show all categories',
  'all_categories': 'all categories',
  'all': 'all',
  'name': 'name',
  'filter': 'filter',
  'brand': 'brand',
  'clear_filters': 'clear filter',
  'no_items_found': 'no items found',
  'error_occurred': 'looks like something went wrong',
  'error': 'error',
  'choose_category': 'choose category',
  'high_to_low': 'high to low',
  'low_to_high': 'low to high',
  'my_cart': 'my cart',
  'quantity': 'quantity',
  'move_to_wishlist': 'move to wishlist',
  'wishlist': 'wishlist',
  'my_wishlist': 'my wishlist',
  'quantity_available': 'quantity available',
  'in_stock': 'in stock',
  'out_of_stock': 'out of stock',
  'about': 'about',
  'faq': 'faq',
  'contact_us': 'contact us',
  'notifications': 'notifications',
  'new_item': 'new item',
  'preloved_item': 'preloved item',
  'description': 'description',
  'specifications': 'specifications',
  'sku': 'sku',
  'related_items': 'related items',
  'new_search': 'new search',
  'back_to_home': 'back to home',
  'welcome_to_momday': 'welcome to momday',
  'my_profile': 'my profile',
  'my_addresses': 'my addresses',
  'location': 'location',
  'advanced_settings': 'advanced settings',
  'welcome': 'welcome',
  'create_an_account': 'create an account',
  'no_worries': 'no worries!',
  'dont_have_an_account': 'don\'t have an account?',
  'select_address': 'select address',
  'add_new_address': 'add new address',
  'add_address': 'add address',
  'pay': 'Pay',
  'pay_with_payfort': 'Pay With Payfort',
  'pay_with_aramex': 'Deliver With Aramex',
  'country': 'country',
  'city': 'city',
  'menu': 'menu',
  'lebanon': 'lebanon',
  'address': 'address',
  'failed_to_add_address': 'failed to add address',
  'enter_less_than_2_lines': 'please enter 2 lines at most',
  'continue_to_payment': 'continue to payment',
  'no_address_selected': 'no address was selected',
  'change_address': 'change address',
  'delete_address': 'delete address',
  'confirm_remove_address': 'are you sure you want to remove the address?',
  'no_addresses': 'you haven\'t added any addresses!',
  'clear_cache': 'clear cache',
  'clear_session_data': 'clear session data',
  'confirm_clear_cache':
      'are you sure you want to clear the cache? this will temporarily make the app slower',
  'confirm_clear_session_data':
      'are you sure you want to clear the session data? this will log you out',
  'advanced_settings_warning':
      'only do these operations if instructed by the support engineers',
  'add_your_review': 'add your review',
  'already_reviewed': 'you have already reviewed this product',
  'share_your_review': 'share your review about this item',
  'rate_this_item': 'rate this item',
  'provide_rating': 'please provide a rating',
  'review_length_restrictions':
      'the review must be between 25 and 1000 characters',
  'review_submitted':
      'your review has been submitted. It will be visible once the admin approves it',
  'edit': 'edit',
  'change_password': 'change password',
  'save_changes': 'save changes',
  'in_my_wishlist': 'in my wishlist',
  'in_my_cart': 'in my cart',
  'add_to_my_store': 'add to my store',
  'in_my_my_store': 'in my store',
  'remove_from_my_store': 'remove from my store',
  'my_store': 'my store',
  'sort_by': 'sort by',
  'apply_filters': 'apply filters',
  'category': 'category',
  'products': 'products',
  'coming_soon': 'coming soon',
  'try_again': 'try again',
  'report_issue': 'report issue',
  'no_related_products': 'no related products found',
  'view_all': 'view all',
  'view_more': 'view more',
  'moms_best_daily_kit': 'Mom\'s best daily kit',
  'momday_description':
      'Check the variety of kid’s items you need, the on-going activities, and experience motherhood like your favourite celebrities!',
  'visit_website': 'visit website',
  'read_full_article': 'read full article',
  'write_your_comment': 'write your comment',
  'add_comment': 'add comment',
  'comment_single': 'comment',
  'comment_plural': 'comments',
  'like_this_post': 'like this post',
  'comment_on_this_post': 'comment on this post',
  'view_details': 'view details',
  'event_details': 'event details',
  'view_author_bio': 'view author\'s bio',
  'biography': 'biography',
  'reply': 'reply',
  'view_replies': 'view replies',
  'hide_replies': 'hide replies',
  'add_your_reply': 'add your reply',
  'my_list': 'my list',
  'upload_image': 'upload photo',
  'upload_video': 'upload video',
  'upload_image_header': 'make sure to upload at most 4 images for your item',
  "upload_video_header":
      "Upload a 5 seconds video that shows your item's details.",
  'photos': 'photos',
  'video': 'video',
  'image_from_gallery': 'upload from gallery',
  'image_from_camera': 'take a photo',
  'video_from_gallery': 'upload from gallery',
  'video_from_camera': 'take a video',
  'delete_attachment': 'delete attachment',
  'delete_attachment_confirm': 'are you sure you want to delete this file?',
  'delete': 'delete',
  'next': 'next',
  'previous': 'previous',
  'contact_info': 'contact information',
  'contact_info_details': 'add your email, phone number, and pick up location',
  'contact_info_disclaimer':
      'please note that your phone number will not appear in your post, we will only use it to contact you to arrange pick up of your item',
  'phone': 'phone',
  'pickup': 'pick up Location',
  'pickup_hint': 'write the pick up Location',
  'donate': 'donate',
  'donate_to': 'donate to',
  'donation_ask': 'would you like to donate to charity?',
  'donation_msg':
      'by donating you agree that the profits of your item will be fully dedicated to the charity.',
  'donation_msg_buyer':
      'The profits of this item will be fully dedicated to charity',
  'no_thanks': 'no thanks',
  'item_name': 'item name',
  'item_name_hint': "write the item's name",
  'description_hint': 'describe the item in a few words',
  'brand_hint': "choose the brand",
  'condition_hint': "choose the item's condition",
  'subcategory_hint': "choose the item's subcategory",
  'category_hint': "choose the item's category",
  'type': 'type',
  'good': 'good',
  'fair': 'fair',
  'excellent': 'excellent',
  'size': 'size',
  'size_hint': 'size',
  'color': 'color',
  'color_hint': 'color',
  'price_hint': 'write the price of the item',
  'add_item': 'add item',
  'donated': 'donated',
  'condition': 'condition',
  'loading_video': 'loading video',
  'preview_video': 'preview video',
  'close': 'close',
  'pending': 'pending',
  'inactive': 'inactive',
  'active': 'active',
  'sold': 'sold',
  'charity': 'charity',
  'delete_myitem': 'delete item',
  'delete_myitem_confirm': 'are you sure you want to delete this item?',
  'deactivate_myitem': 'deactivate item',
  'deactivate_myitem_confirm': 'are you sure you want to deactivate this item?',
  'deactivate': 'deactivate',
  'activate': 'activate',
  'specify_options': 'please specify the following options',
  'select_option': 'please select',
  'invalid_phoneNumber': 'invalid phone number',
  'video_required': 'please upload a video',
  'image_required': 'please upload at least one image',
  'expires': 'expires',
  'view_remark': 'view remark',
  'ok': 'ok',
  'dimensions': 'dimensions',
  'width': 'width',
  'height': 'height',
  'length': 'length',
  'weight': 'weight',
  'dimensions_unit': 'dimensions unit',
  'weight_unit': 'weight unit',
  'uploading_attachment': 'uploading attachment',
  'comment_submitted':
      'your comment has been submitted. it will be visible once the admin approves it',
  'comment_error': 'error posting comment. try again later.',
  'submit': 'submit',
  'product_attributes': 'product attributes',
  'rejected': 'rejected',
  'reward_points': 'Reward points',
  'final_price': 'final item price'
};
